import Head from 'next/head'

import Header from '../components/header'
import Banner from '../components/banner'
import About from '../components/about'
import Projects from '../components/projects'
import Quote from '../components/quote'
import Contact from '../components/contact'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>BM - Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <About />
      <Projects />
      <Quote />
      <Contact />
      <Footer />
    </div>
  )
}
